n = input('Digite algo ')
print('O que você digitou é alfanumérico?', n.isalnum())
print('O que você digitou é alfabético?', n.isalpha())
print('O que você digitou é ascii?', n.isascii())
print('O que você digitou é decimal?', n.isdecimal())
print('O que você digitou é digito?', n.isdigit())
print('O que você digitou é indentifier?', n.isidentifier())
print('O que você digitou é printável?', n.isprintable())
print('O que você digitou é minúsculo?', n.islower())
print('O que você digitou é maiúsculo?', n.isupper())
print('O que você digitou é espaço?', n.isspace())
print('O que você digitou é título?', n.istitle())
